name: mc_rcon_dart
description: A Dart SDK for interacting with a Minecraft server using the RCON protocol.
version: 0.0.1
homepage: https://github.com/aidanlok/mc_rcon
repository: https://github.com/aidanlok/mc_rcon
issue_tracker: https://github.com/aidanlok/mc_rcon/issues

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0