name: mc_rcon_dart
description: A Dart SDK for interacting with a Minecraft server using the RCON protocol.
version: 1.0.3
homepage: https://github.com/aidanlok/mc_rcon
repository: https://github.com/aidanlok/mc_rcon
issue_tracker: https://github.com/aidanlok/mc_rcon/issues

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0